---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: 'jdbc:h2:mem:catalog;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password: sa
    driver-class-name: 'org.h2.Driver'
    initialize: 'true'
    initialization-mode: always
    schema: 'classpath:/schema.sql'
    continue-on-error: 'true'
inventory:
  url: 'http://localhost:8080'
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: openshift-dev
  datasource:
    url: 'jdbc:postgresql://catalog-database:5432/catalog'
    username: catalog
    password: mysecretpassword
    initialize: 'true'
    initialization-mode: always
    schema: 'classpath:/schema.sql'
    continue-on-error: 'true'
inventory:
  url: 'inventory.coolstore-inventory-dev.svc.cluster.local'
management:
  metrics:
    export:
      prometheus:
        enabled: 'true'
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics,prometheus'
feign:
  hystrix:
    enabled: 'true'
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: openshift
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    initialize: 'true'
    initialization-mode: always
    schema: 'classpath:/schema.sql'
    continue-on-error: 'true'
inventory:
  url: ${INVENTORY_URL}
management:
  metrics:
    export:
      prometheus:
        enabled: 'true'
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics,prometheus'
feign:
  hystrix:
    enabled: 'true'
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000